# Decision Functions-----------------------------------------------------------------------------
getAdptChoice <- function(station.gauge, decisionMonth, currentYear, estForage){
  "
  reads in precip to decision month and applys a rule for adaptation
  Inputs:
  station.gauge: a list of data generated by getStationGauge
  decisionMonth: month the adaptation must be made
  currentYear: the current year
  "

  if(estForage < 1){
    adptChoice <- "feed"
  }else{
    adptChoice <- "noAdpt"
  }
  return(adptChoice)
}

getCalfSales <- function(station.gauge, adpt_choice, decisionMonth, currentYear, calf.sell, estForage){
  "
  reads in precip to decision month and applys a rule for the number of calves to sell
  Inputs:
  station.gauge: a list of data generated by getStationGauge
  decisionMonth: month the adaptation must be made
  adpt_choice: whether or not adaptation was taken in the previous year
  currentYear: the current year

  Returns:
  calf.sell: the percentage of calves to sell
  "
  
  if(estForage < 1 & adpt_choice == "noAdpt"){
    calf.sell <- .9
  }
  return(calf.sell)
}

getInsChoice <- function(){
  "
  Returns a choice about ins based on some number of rules...not sure what this should look like
  Inputs:
  Not sure what we want to have for this one

  Returns:
  insChoice: a boolean for whether insurance is being purchased for the current year
  "
  insChoice <- T
  return(insChoice)
}

getBuyDecision <- function(){
  "
  Returns a choice repurchaseing cows based on some number of rules...
  not sure what this should look like
  Inputs:
  Not sure what we want to have for this one

  Returns:
  buyChoice: a boolean for whether to rebuy cows for the current year
  "
  buyChoice <- T
  return(buyChoice)
}
  
