# Collecting unused functions

noIns <- function(){
  purchaseInsurance <<- FALSE
  indem <<- lapply(indem, function(x){
    x[, c("producer_prem", "indemnity", "full_prem") := 0]
    return(x)
  })
  indemprac <<- lapply(indemprac, function(x){
    x[, c("producer_prem", "indemnity", "full_prem") := 0]
    return(x)
  })
}

getAdptChoice <- function(station.gauge, decisionMonth, currentYear, estForage){
  "
  reads in precip to decision month and applys a rule for adaptation
  Inputs:
  station.gauge: a list of data generated by getStationGauge
  decisionMonth: month the adaptation must be made
  currentYear: the current year
  "
  
  if(estForage < 1){
    adptChoice <- "feed"
  }else{
    adptChoice <- "noAdpt"
  }
  return(adptChoice)
}


forageWeights2Intervals<-function(fpwt){
  
  "
  Helper function for binning monthly
  forage weights into 2-month intervals
  matching the RMA insurance.
  "
  
  fpwt_iv=c()
  for(m in 1:11){
    
    fpwt_iv=c(fpwt_iv,(sum(fpwt[m],fpwt[m+1])/2)) # need to calc mean manually - not sure why
    names(fpwt_iv[m])=paste0("i",m)
    
  }
  
  return(fpwt_iv)
  
}

CalculateDaysAction <- function(act.st.yr, act.st.m, act.end.yr, act.end.m, drought.action) {
  "
  Function: CalculateDaysAction
  Description: Calculate the number of days rancher pays for a drought adaptation action.
  NOTE: This function assumes that the actions take place only in one year.
  
  Inputs:
  act.st.yr = Year the action starts
  act.st.m = Month the action starts
  act.end.yr = Year the action ends
  act.end.m = Month the action ends
  drought.action = ??
  
  Outputs:
  days.act = Number of days drought adaptation action takes place (days)
  "
  
  # Start and End month assumes that action starts/stops on the first of the month
  
  # Error handling
  if (act.st.yr < 1) {
    stop("Action start year ", act.st.yr, "is not greater than 0")
  }
  if (act.st.yr > act.end.yr | act.st.yr == act.end.yr & act.st.m > act.end.m) {
    stop("Action end occurs before action start")
  }
  if (act.st.m < 1 | act.st.m > 12 | act.end.m < 1 | act.end.m > 12) {
    stop("Invalid action start or end month (not between 1 and 12)")
  }
  
  if (act.st.yr == act.end.yr) {
    days.act <- (act.end.m - act.st.m) * 30
  }
  
  # TEMPORARY ERROR: While the model is not equipped to handle multi-year droughts, we will not allow drought
  #  adaptation across multiple years.
  if (act.st.yr != act.end.yr) {
    stop("Model not equipped for multi-year drought adaptation. act.st.yr must equal act.end.yr")
  }
  
  days.act.vect <- days.act * drought.action #Creates a vector of days of action
  days.act.vect
}

CalculateBaseOpCosts <- function(herd, cow.cost) {
  base.op.cost <- herd * cow.cost
  return(base.op.cost)
}

CalculateRentPastRevenue <- function(herd, wn.succ, calf.sell, normal.wn.wt, calf.loss, calf.wt.adj, p.wn) {
  "
  CalculateRentPastRevenue
  Description: Calculates calf sale revenues after trucking pairs to rented pastures
  
  Inputs:
  calf.loss = Additional calf deaths due to transport stress (head of calves)
  calf.wt.adj = Adjustment for calf weaning weights (%)
  calf.sell = Average percentage of calves sold (%)
  wn.wt = Average weight at weaning (pounds)
  p.wn = Expected sale price of calves ($/pound)
  herd = Size of herd (head of cows, does not include calves)
  wn.succ = Vector of reproductive success percentages that measures how many
  cows in the herd successfully get pregnant, give birth, and wean their calves
  
  Outputs:
  rev.rentpast = Change in revenue due to mortality and weight loss from trucking to rented pasture
  "
  # Number of calves sold after accounting for calf mortality in transport
  calf.sales.num <- (herd * wn.succ * calf.sell) - calf.loss
  
  # Selling weight after accounting for weight loss due to transport stress
  sell.wt <- normal.wn.wt * (1 + calf.wt.adj)
  
  # Expected calf sale revenues
  rev.rentpast <- calf.sales.num * sell.wt * p.wn
  rev.rentpast
}

# Option 3: Sell Pairs & Replace
CalculateSellPrsCost <- function(op.cost.adj, herd, sell.cost, base.op.cost, herdless.op.cost) {
  "
  Function: CalculateSellPrsCost
  Description: Calculates the operating costs to sell pairs in year 1 and replacing cows in year 3
  NOTE: It is assumed that cows are replaced on last day of the second year after they are sold.
  For example, cows sold in 2011 are replaced on 12/31/2013.
  
  Inputs:
  op.cost.adj = Change in operating costs in year 1 per cow ($/cow/year)
  sell.cost = Selling cost per cow ($/cow) NOTE: DO WE COUNT SELLING COSTS IN A NORMAL YEAR? ARE THESE ADDITIONAL?
  herd = Size of herd (head of cows, does not include calves)
  base.cost = Baseline annual cost of operating ranch with full herd ($/year)
  fixed.op.cost = Fixed operating costs for a year without a herd ($/year)
  
  Outputs:
  cost.sellprs = 5x1 vector of changes in operating costs for years 1 through 5 from selling pairs in year 1 and replacing them at the end of year 3
  "
  cost.sellprs <- NULL
  cost.sellprs[1] <- base.op.cost + op.cost.adj * herd + sell.cost * herd  # CORRECT CODE!!! # Yr 1 operating costs includes a reduction in operating cost from not having the herd and the additional cost to sell cows
  # cost.sellprs[1] <- base.op.cost + op.cost.adj * herd  # INCORRECT CODE (replicates excel's exclusion of herd selling costs)
  cost.sellprs[2] <- herdless.op.cost  # fixed 'herdless' operating costs
  cost.sellprs[3] <- herdless.op.cost  # fixed 'herdless' operating costs
  cost.sellprs[4:5] <- base.op.cost  # Yr 4 & 5 change in op costs are assumed to be normal
  
  cost.sellprs
}

CalculateSellPrsRev <- function(base.sales, herd, wn.succ, calf.wt, p.calf.t0) {
  "
  Function: CalculateSellPrsRev
  Description: Calculates calf sales revenues due to selling pairs and replacing cows for years 1 through 3
  NOTE: It is assumed that cows are replaced on last day of the second year after they are sold.
  For example, cows sold in 2011 are replaced on 12/31/2013.
  
  Inputs:
  base.sales = Calf sales in a normal year ($/year)
  p.wn.t0 = Current sale price calves ($/pound)
  herd = Size of herd (head of cows, does not include calves)
  wn.succ = Average percentage of cows that successfully wean calves (%)
  calf.wt = Average 'current' weight of calves (pounds)
  
  Outputs:
  rev.sellprs = 5x1 vector of calf revenues for years 1 through 5.
  "
  # Calf sales revenues
  calf.sales <- rep(NA,5)
  for (i in 1:5) {
    if(i == 1) {
      calf.sales[i] <- herd * wn.succ * calf.wt * p.calf.t0
    }
    if(i == 2 | i == 3) {
      calf.sales[i] <- 0
    }
    if(i > 3) {
      calf.sales[i] <- base.sales[i]
    }
  }
  calf.sales
}