# Collecting unused functions

noIns <- function(){
  purchaseInsurance <<- FALSE
  indem <<- lapply(indem, function(x){
    x[, c("producer_prem", "indemnity", "full_prem") := 0]
    return(x)
  })
  indemprac <<- lapply(indemprac, function(x){
    x[, c("producer_prem", "indemnity", "full_prem") := 0]
    return(x)
  })
}

getAdptChoice <- function(station.gauge, decisionMonth, currentYear, estForage){
  "
  reads in precip to decision month and applys a rule for adaptation
  Inputs:
  station.gauge: a list of data generated by getStationGauge
  decisionMonth: month the adaptation must be made
  currentYear: the current year
  "
  
  if(estForage < 1){
    adptChoice <- "feed"
  }else{
    adptChoice <- "noAdpt"
  }
  return(adptChoice)
}


forageWeights2Intervals<-function(fpwt){
  
  "
  Helper function for binning monthly
  forage weights into 2-month intervals
  matching the RMA insurance.
  "
  
  fpwt_iv=c()
  for(m in 1:11){
    
    fpwt_iv=c(fpwt_iv,(sum(fpwt[m],fpwt[m+1])/2)) # need to calc mean manually - not sure why
    names(fpwt_iv[m])=paste0("i",m)
    
  }
  
  return(fpwt_iv)
  
}